//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IServiceLibrary")]
public interface IServiceLibrary
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLibrary/GetNumberOfOccurences", ReplyAction="http://tempuri.org/IServiceLibrary/GetNumberOfOccurencesResponse")]
    int GetNumberOfOccurences(string firstString, string secondString);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLibrary/GetNumberOfOccurences", ReplyAction="http://tempuri.org/IServiceLibrary/GetNumberOfOccurencesResponse")]
    System.Threading.Tasks.Task<int> GetNumberOfOccurencesAsync(string firstString, string secondString);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IServiceLibraryChannel : IServiceLibrary, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ServiceLibraryClient : System.ServiceModel.ClientBase<IServiceLibrary>, IServiceLibrary
{
    
    public ServiceLibraryClient()
    {
    }
    
    public ServiceLibraryClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServiceLibraryClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceLibraryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceLibraryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int GetNumberOfOccurences(string firstString, string secondString)
    {
        return base.Channel.GetNumberOfOccurences(firstString, secondString);
    }
    
    public System.Threading.Tasks.Task<int> GetNumberOfOccurencesAsync(string firstString, string secondString)
    {
        return base.Channel.GetNumberOfOccurencesAsync(firstString, secondString);
    }
}
