//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDateService.Client.WcfDateServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfDateServiceReference.IServiceDateDisplayer")]
    public interface IServiceDateDisplayer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDateDisplayer/GetDayAsBulgarianString", ReplyAction="http://tempuri.org/IServiceDateDisplayer/GetDayAsBulgarianStringResponse")]
        string GetDayAsBulgarianString(System.DateTime dateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDateDisplayer/GetDayAsBulgarianString", ReplyAction="http://tempuri.org/IServiceDateDisplayer/GetDayAsBulgarianStringResponse")]
        System.Threading.Tasks.Task<string> GetDayAsBulgarianStringAsync(System.DateTime dateTime);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDateDisplayerChannel : WcfDateService.Client.WcfDateServiceReference.IServiceDateDisplayer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDateDisplayerClient : System.ServiceModel.ClientBase<WcfDateService.Client.WcfDateServiceReference.IServiceDateDisplayer>, WcfDateService.Client.WcfDateServiceReference.IServiceDateDisplayer {
        
        public ServiceDateDisplayerClient() {
        }
        
        public ServiceDateDisplayerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDateDisplayerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDateDisplayerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDateDisplayerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDayAsBulgarianString(System.DateTime dateTime) {
            return base.Channel.GetDayAsBulgarianString(dateTime);
        }
        
        public System.Threading.Tasks.Task<string> GetDayAsBulgarianStringAsync(System.DateTime dateTime) {
            return base.Channel.GetDayAsBulgarianStringAsync(dateTime);
        }
    }
}
