//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionsHistory
    {
        public int TransactionId { get; set; }
        public decimal OldCash { get; set; }
        public decimal NewCash { get; set; }
        public int CardAccountId { get; set; }
    
        public virtual CardAccount CardAccount { get; set; }
    }
}
